export type OrderStatus = "bloqueado" | "coordinacion" | "completado";
export type OrderFilter = "gestion" | "completados" | "todos";

export interface OrderLine {
  id: string;
  product: string;
  quantity: number;
  preparation?: string;
}

export interface OperationOrder {
  id: string;
  reference: string;
  client: string;
  product: string;
  requested: number;
  delivered: number;
  pending: number;
  status: OrderStatus;
  statusLabel: "Bloqueado" | "En coordinación" | "Completado";
  dateLabel: string;
  transport: string;
  supply: string;
  preparation: string;
  logistics: string;
  delivery: string;
  action: string;
  remittance?: string;
  lines: OrderLine[];
  source: string;
}

export const orders: OperationOrder[] = [
  {
    id: "frutura-74",
    reference: "Plan 74",
    client: "Frutura",
    product: "Pallet 122 × 102",
    requested: 600,
    delivered: 0,
    pending: 600,
    status: "bloqueado",
    statusLabel: "Bloqueado",
    dateLabel: "Viernes 14",
    transport: "Linares",
    supply: "Los pallets previstos no llegaron",
    preparation: "Marcado requerido",
    logistics: "Viaje con Linares detenido",
    delivery: "0 de 600 entregados",
    action: "Reprogramar la entrega cuando ingrese la mercadería.",
    lines: [{ id: "frutura-74-1", product: "Pallet 122 × 102", quantity: 600, preparation: "Marcado" }],
    source: "Plan semanal · fila 74",
  },
  {
    id: "proquimur-63",
    reference: "Plan 63",
    client: "Proquimur",
    product: "Pallet 120 × 100 Mercosur",
    requested: 600,
    delivered: 0,
    pending: 600,
    status: "coordinacion",
    statusLabel: "En coordinación",
    dateLabel: "Martes 11",
    transport: "Linares",
    supply: "600 en stock Palbin · 300 marcados y 300 sin marcar",
    preparation: "300 con HT · 300 sin HT",
    logistics: "Linares asignado",
    delivery: "Pedido en coordinación",
    action: "Coordinar fecha con el cliente y reservar el viaje.",
    lines: [
      { id: "proquimur-63-1", product: "Pallet 120 × 100 Mercosur", quantity: 300, preparation: "Con HT" },
      { id: "proquimur-63-2", product: "Pallet 120 × 100 Mercosur", quantity: 300, preparation: "Sin HT" },
    ],
    source: "Plan semanal · fila 63 / Stock Palbin · fila 19",
  },
  {
    id: "pamer-184833",
    reference: "Orden 184833",
    client: "Pamer",
    product: "Cinco líneas de pallets",
    requested: 500,
    delivered: 500,
    pending: 0,
    status: "completado",
    statusLabel: "Completado",
    dateLabel: "28 de julio",
    transport: "Remito 603",
    supply: "Orden despachada en cinco líneas",
    preparation: "380 sin HT · 120 con HT",
    logistics: "Remito 603",
    delivery: "500 entregados · saldo 0",
    action: "Pedido cerrado.",
    remittance: "603",
    lines: [
      { id: "184833-1", product: "Pallet 100 × 100 doble entrada", quantity: 100, preparation: "Sin HT" },
      { id: "184833-2", product: "Pallet 100 × 100", quantity: 20, preparation: "Con HT" },
      { id: "184833-3", product: "Pallet 120 × 80 doble entrada", quantity: 180, preparation: "Sin HT" },
      { id: "184833-4", product: "Pallet 120 × 130", quantity: 100, preparation: "Sin HT" },
      { id: "184833-5", product: "Pallet 100 × 120 Mercosur", quantity: 100, preparation: "Con HT" },
    ],
    source: "Órdenes Pamer · filas 4–8",
  },
  {
    id: "pamer-641",
    reference: "Remito 641",
    client: "Pamer",
    product: "Seis líneas de pallets",
    requested: 360,
    delivered: 360,
    pending: 0,
    status: "completado",
    statusLabel: "Completado",
    dateLabel: "12 de agosto",
    transport: "Propio",
    supply: "Seis líneas despachadas",
    preparation: "200 sin HT · 160 con HT",
    logistics: "Transporte propio · remito 641",
    delivery: "360 entregados · saldo 0",
    action: "Pedido cerrado.",
    remittance: "641",
    lines: [
      { id: "641-1", product: "Pallet 216 × 110 simple", quantity: 100, preparation: "Con HT" },
      { id: "641-2", product: "Pallet 216 × 110 simple", quantity: 41, preparation: "Sin HT" },
      { id: "641-3", product: "Pallet 100 × 80", quantity: 100, preparation: "Sin HT" },
      { id: "641-4", product: "Pallet 100 × 100", quantity: 59, preparation: "Sin HT" },
      { id: "641-5", product: "Pallet 120 × 80", quantity: 20, preparation: "Con HT" },
      { id: "641-6", product: "Pallet 120 × 90 cerrado", quantity: 40, preparation: "Con HT" },
    ],
    source: "Órdenes Pamer · filas 10–15",
  },
  {
    id: "afb-62",
    reference: "Plan 62",
    client: "AFB",
    product: "Pallet 120 × 100 Mercosur cepillado",
    requested: 600,
    delivered: 600,
    pending: 0,
    status: "completado",
    statusLabel: "Completado",
    dateLabel: "Martes 11",
    transport: "Linares",
    supply: "Pedido completo",
    preparation: "Mercosur cepillado",
    logistics: "Linares · un viaje",
    delivery: "600 entregados",
    action: "Pedido cerrado.",
    lines: [{ id: "afb-62-1", product: "Pallet 120 × 100 Mercosur cepillado", quantity: 600 }],
    source: "Plan semanal · fila 62",
  },
  {
    id: "granja-pocha-65",
    reference: "Plan 65",
    client: "Granja Pocha",
    product: "Punto rojo y Mercosur exportación",
    requested: 600,
    delivered: 600,
    pending: 0,
    status: "completado",
    statusLabel: "Completado",
    dateLabel: "Miércoles 12",
    transport: "Linares",
    supply: "Dos líneas completas",
    preparation: "400 punto rojo · 200 Mercosur exportación",
    logistics: "Linares · un viaje",
    delivery: "600 entregados",
    action: "Pedido cerrado.",
    lines: [
      { id: "pocha-65-1", product: "Pallet punto rojo 120 × 100", quantity: 400 },
      { id: "pocha-65-2", product: "Pallet Mercosur exportación 120 × 100", quantity: 200 },
    ],
    source: "Plan semanal · fila 65",
  },
  {
    id: "forestal-66",
    reference: "Plan 66",
    client: "Forestal Oriental",
    product: "Pallet 120 × 130",
    requested: 50,
    delivered: 50,
    pending: 0,
    status: "completado",
    statusLabel: "Completado",
    dateLabel: "Miércoles 12",
    transport: "Matías",
    supply: "Pedido completo",
    preparation: "Sin HT · sin corte de esquina · sin rebaje",
    logistics: "Matías · un viaje",
    delivery: "50 entregados",
    action: "Pedido cerrado.",
    lines: [{ id: "forestal-66-1", product: "Pallet 120 × 130", quantity: 50, preparation: "Sin HT" }],
    source: "Plan semanal · fila 66",
  },
  {
    id: "frutura-67",
    reference: "Plan 67",
    client: "Frutura",
    product: "Pallet 122 × 102",
    requested: 518,
    delivered: 518,
    pending: 0,
    status: "completado",
    statusLabel: "Completado",
    dateLabel: "Miércoles 12",
    transport: "Milton",
    supply: "Pedido completo",
    preparation: "Pallet 122 × 102",
    logistics: "Milton · un viaje",
    delivery: "518 entregados",
    action: "Pedido cerrado.",
    lines: [{ id: "frutura-67-1", product: "Pallet 122 × 102", quantity: 518 }],
    source: "Plan semanal · fila 67",
  },
  {
    id: "frutura-69",
    reference: "Plan 69",
    client: "Frutura",
    product: "Pallet 120 × 100",
    requested: 600,
    delivered: 600,
    pending: 0,
    status: "completado",
    statusLabel: "Completado",
    dateLabel: "Jueves 13",
    transport: "Linares",
    supply: "Pedido completo",
    preparation: "Pallet 120 × 100",
    logistics: "Linares · un viaje",
    delivery: "600 entregados",
    action: "Pedido cerrado.",
    lines: [{ id: "frutura-69-1", product: "Pallet 120 × 100", quantity: 600 }],
    source: "Plan semanal · fila 69",
  },
  {
    id: "azucitrus-75",
    reference: "Plan 75",
    client: "Azucitrus",
    product: "Pallet 120 × 100",
    requested: 600,
    delivered: 600,
    pending: 0,
    status: "completado",
    statusLabel: "Completado",
    dateLabel: "Viernes 14",
    transport: "Linares",
    supply: "Pedido completo",
    preparation: "Pallet 120 × 100",
    logistics: "Linares · un viaje",
    delivery: "600 entregados",
    action: "Pedido cerrado.",
    lines: [{ id: "azucitrus-75-1", product: "Pallet 120 × 100", quantity: 600 }],
    source: "Plan semanal · fila 75",
  },
  {
    id: "san-miguel-76",
    reference: "Plan 76",
    client: "San Miguel",
    product: "Dos medidas de pallets",
    requested: 360,
    delivered: 360,
    pending: 0,
    status: "completado",
    statusLabel: "Completado",
    dateLabel: "Viernes 14",
    transport: "Milton",
    supply: "Dos líneas completas",
    preparation: "250 de 120 × 120 · 110 de 116,5 × 114",
    logistics: "Milton · un viaje",
    delivery: "360 entregados",
    action: "Pedido cerrado.",
    lines: [
      { id: "san-miguel-76-1", product: "Pallet 120 × 120", quantity: 250 },
      { id: "san-miguel-76-2", product: "Pallet 116,5 × 114", quantity: 110 },
    ],
    source: "Plan semanal · fila 76",
  },
  {
    id: "pontevedra-79",
    reference: "Plan 79",
    client: "Pontevedra",
    product: "Pallet Mercosur con HT",
    requested: 150,
    delivered: 150,
    pending: 0,
    status: "completado",
    statusLabel: "Completado",
    dateLabel: "Sábado 15",
    transport: "Matías",
    supply: "Pedido completo",
    preparation: "Mercosur con HT",
    logistics: "Matías · un viaje",
    delivery: "150 entregados",
    action: "Pedido cerrado.",
    lines: [{ id: "pontevedra-79-1", product: "Pallet Mercosur", quantity: 150, preparation: "Con HT" }],
    source: "Plan semanal · fila 79",
  },
];

export const orderFilters: Array<{ id: OrderFilter; label: string }> = [
  { id: "gestion", label: "En gestión" },
  { id: "completados", label: "Completados" },
  { id: "todos", label: "Todos" },
];
