alter table public.products
  add column if not exists requires_treatment boolean not null default false;

update public.products
set requires_treatment = treatment in ('Marcado', 'HT', 'Marcado y HT')
where treatment is not null;

alter table public.orders drop constraint if exists orders_required_operations_check;

update public.orders
set required_operations = array(
  select distinct case when operation in ('marking', 'ht') then 'treatment' else operation end
  from unnest(coalesce(required_operations, array['assembly']::text[])) operation
  order by 1
)
where coalesce(required_operations, array[]::text[]) && array['marking', 'ht']::text[];

alter table public.orders add constraint orders_required_operations_check
  check (cardinality(required_operations) > 0 and required_operations <@ array['assembly', 'treatment']::text[]);

create table public.treatment_batches (
  id bigint generated by default as identity primary key,
  product_id text not null references public.products(id) on delete restrict,
  client_product_id bigint references public.client_products(id) on delete restrict,
  order_line_id text references public.order_lines(id) on delete restrict,
  quantity integer not null check (quantity > 0),
  performed_at timestamptz not null,
  responsible text not null check (nullif(trim(responsible), '') is not null),
  status text not null check (status in ('posted', 'rejected', 'reversal')),
  note text,
  reversal_of_batch_id bigint unique references public.treatment_batches(id) on delete restrict,
  created_at timestamptz not null default now(),
  check ((status = 'reversal') = (reversal_of_batch_id is not null)),
  check (status = 'posted' or nullif(trim(note), '') is not null),
  check (client_product_id is not null or nullif(trim(note), '') is not null)
);

create table public.treatment_control_checks (
  id bigint generated by default as identity primary key,
  batch_id bigint not null references public.treatment_batches(id) on delete restrict,
  control_id bigint not null references public.client_product_controls(id) on delete restrict,
  control_title_snapshot text not null check (nullif(trim(control_title_snapshot), '') is not null),
  result text not null check (result in ('pass', 'fail')),
  note text,
  created_at timestamptz not null default now(),
  unique (batch_id, control_id),
  check (result = 'pass' or nullif(trim(note), '') is not null)
);

create table public.stock_movements (
  id bigint generated by default as identity primary key,
  product_id text not null references public.products(id) on delete restrict,
  stock_state text not null check (stock_state in ('pending_treatment', 'ready')),
  quantity integer not null check (quantity <> 0),
  movement_type text not null check (movement_type in (
    'production_receipt', 'treatment_out', 'treatment_in',
    'treatment_reversal_out', 'treatment_reversal_in'
  )),
  treatment_batch_id bigint references public.treatment_batches(id) on delete restrict,
  production_allocation_id bigint references public.production_allocations(id) on delete restrict,
  transformation_id uuid not null default gen_random_uuid(),
  performed_at timestamptz not null,
  responsible text not null check (nullif(trim(responsible), '') is not null),
  note text,
  correction_of_movement_id bigint references public.stock_movements(id) on delete restrict,
  created_at timestamptz not null default now(),
  check (
    (movement_type = 'production_receipt' and quantity > 0 and treatment_batch_id is null and production_allocation_id is not null)
    or (movement_type = 'treatment_out' and stock_state = 'pending_treatment' and quantity < 0 and treatment_batch_id is not null)
    or (movement_type = 'treatment_in' and stock_state = 'ready' and quantity > 0 and treatment_batch_id is not null)
    or (movement_type = 'treatment_reversal_out' and stock_state = 'ready' and quantity < 0 and treatment_batch_id is not null)
    or (movement_type = 'treatment_reversal_in' and stock_state = 'pending_treatment' and quantity > 0 and treatment_batch_id is not null)
  )
);

create index treatment_batches_product_performed_idx on public.treatment_batches(product_id, performed_at desc);
create index treatment_batches_client_product_idx on public.treatment_batches(client_product_id) where client_product_id is not null;
create index treatment_batches_order_line_idx on public.treatment_batches(order_line_id) where order_line_id is not null;
create index treatment_control_checks_batch_idx on public.treatment_control_checks(batch_id);
create index treatment_control_checks_control_idx on public.treatment_control_checks(control_id);
create index stock_movements_product_state_performed_idx on public.stock_movements(product_id, stock_state, performed_at desc);
create index stock_movements_treatment_batch_idx on public.stock_movements(treatment_batch_id) where treatment_batch_id is not null;
create index stock_movements_correction_idx on public.stock_movements(correction_of_movement_id) where correction_of_movement_id is not null;
create unique index stock_movements_production_allocation_unique
  on public.stock_movements(production_allocation_id)
  where movement_type = 'production_receipt';

alter table public.treatment_batches enable row level security;
alter table public.treatment_control_checks enable row level security;
alter table public.stock_movements enable row level security;

create policy treatment_batches_read on public.treatment_batches for select to anon, authenticated using (true);
create policy treatment_control_checks_read on public.treatment_control_checks for select to anon, authenticated using (true);
create policy stock_movements_read on public.stock_movements for select to anon, authenticated using (true);

grant select on public.treatment_batches, public.treatment_control_checks, public.stock_movements to anon, authenticated;
grant select, insert on public.treatment_batches, public.treatment_control_checks, public.stock_movements to service_role;
grant usage, select on sequence public.treatment_batches_id_seq, public.treatment_control_checks_id_seq, public.stock_movements_id_seq to service_role;
revoke update, delete on public.treatment_batches, public.treatment_control_checks, public.stock_movements from public, anon, authenticated, service_role;

create or replace function public.prevent_stock_movement_mutation()
returns trigger language plpgsql security invoker set search_path = public as $$
begin
  raise exception 'Los movimientos de stock son inmutables; registre una corrección.';
end; $$;

create trigger stock_movements_append_only
before update or delete on public.stock_movements
for each row execute function public.prevent_stock_movement_mutation();

revoke execute on function public.prevent_stock_movement_mutation() from public, anon, authenticated;

create or replace function public.record_treatment_batch_v1(
  p_product_id text,
  p_client_product_id bigint,
  p_order_line_id text,
  p_quantity integer,
  p_performed_at timestamptz,
  p_responsible text,
  p_note text,
  p_controls jsonb
) returns jsonb language plpgsql security invoker set search_path = public as $$
declare
  v_requires_treatment boolean;
  v_client_product_id bigint := p_client_product_id;
  v_line_product_id text;
  v_line_client_product_id bigint;
  v_controls jsonb := coalesce(p_controls, '[]'::jsonb);
  v_control jsonb;
  v_control_row public.client_product_controls%rowtype;
  v_expected_controls integer := 0;
  v_has_failure boolean := false;
  v_status text;
  v_batch_id bigint;
  v_transformation_id uuid := gen_random_uuid();
  v_pending_before integer := 0;
  v_ready_before integer := 0;
begin
  if p_quantity is null or p_quantity <= 0 then raise exception 'La cantidad debe ser mayor a cero.'; end if;
  if nullif(trim(p_responsible), '') is null then raise exception 'Indique quién realizó el tratamiento.'; end if;
  if jsonb_typeof(v_controls) <> 'array' then raise exception 'El formato de controles es inválido.'; end if;

  select requires_treatment into v_requires_treatment from public.products where id = p_product_id;
  if not found then raise exception 'Producto no encontrado.'; end if;
  if not v_requires_treatment then raise exception 'El producto no requiere Tratamiento HT / Marcado.'; end if;

  if p_order_line_id is not null then
    select product_id, client_product_id into v_line_product_id, v_line_client_product_id
    from public.order_lines where id = p_order_line_id for share;
    if not found then raise exception 'Línea de pedido no encontrada.'; end if;
    if v_line_product_id is distinct from p_product_id then raise exception 'La línea no corresponde al producto seleccionado.'; end if;
    if v_line_client_product_id is null then raise exception 'La línea no tiene cliente/producto vinculado.'; end if;
    if p_client_product_id is not null and p_client_product_id <> v_line_client_product_id then raise exception 'La línea no corresponde al cliente/producto seleccionado.'; end if;
    v_client_product_id := v_line_client_product_id;
  end if;

  if v_client_product_id is not null then
    if not exists (
      select 1 from public.client_products
      where id = v_client_product_id and product_id = p_product_id and active
    ) then raise exception 'El cliente/producto no está activo o no coincide con el producto.'; end if;
    select count(*) into v_expected_controls
    from public.client_product_controls where client_product_id = v_client_product_id and active;
    if v_expected_controls = 0 or jsonb_array_length(v_controls) <> v_expected_controls then
      raise exception 'Complete todos los puntos de control activos.';
    end if;
    for v_control in select * from jsonb_array_elements(v_controls) loop
      select * into v_control_row
      from public.client_product_controls
      where id = (v_control->>'controlId')::bigint and client_product_id = v_client_product_id and active;
      if not found then raise exception 'Uno de los controles no pertenece a la ficha seleccionada.'; end if;
      if (v_control->>'result') not in ('pass', 'fail') then raise exception 'Indique Conforme o No conforme en cada control.'; end if;
      if (v_control->>'result') = 'fail' then
        v_has_failure := true;
        if nullif(trim(v_control->>'note'), '') is null then raise exception 'Explique cada control no conforme.'; end if;
      end if;
    end loop;
  else
    if jsonb_array_length(v_controls) <> 0 then raise exception 'Stock general no admite controles específicos de cliente.'; end if;
    if nullif(trim(p_note), '') is null then raise exception 'Justifique el registro como stock general.'; end if;
  end if;

  if v_has_failure and nullif(trim(p_note), '') is null then raise exception 'Explique el rechazo del lote.'; end if;
  v_status := case when v_has_failure then 'rejected' else 'posted' end;

  if v_status = 'posted' then
    perform 1 from public.products where id = p_product_id for update;
    select coalesce(sum(quantity), 0) into v_pending_before
    from public.stock_movements where product_id = p_product_id and stock_state = 'pending_treatment';
    select coalesce(sum(quantity), 0) into v_ready_before
    from public.stock_movements where product_id = p_product_id and stock_state = 'ready';
    if v_pending_before < p_quantity then raise exception 'El stock pendiente no alcanza para confirmar el tratamiento.'; end if;
  else
    select coalesce(sum(quantity), 0) into v_pending_before
    from public.stock_movements where product_id = p_product_id and stock_state = 'pending_treatment';
    select coalesce(sum(quantity), 0) into v_ready_before
    from public.stock_movements where product_id = p_product_id and stock_state = 'ready';
  end if;

  insert into public.treatment_batches(
    product_id, client_product_id, order_line_id, quantity, performed_at, responsible, status, note
  ) values (
    p_product_id, v_client_product_id, p_order_line_id, p_quantity, coalesce(p_performed_at, now()), trim(p_responsible), v_status, nullif(trim(p_note), '')
  ) returning id into v_batch_id;

  if v_client_product_id is not null then
    for v_control in select * from jsonb_array_elements(v_controls) loop
      select * into v_control_row from public.client_product_controls where id = (v_control->>'controlId')::bigint;
      insert into public.treatment_control_checks(batch_id, control_id, control_title_snapshot, result, note)
      values (v_batch_id, v_control_row.id, v_control_row.title, v_control->>'result', nullif(trim(v_control->>'note'), ''));
    end loop;
  end if;

  if v_status = 'posted' then
    insert into public.stock_movements(product_id, stock_state, quantity, movement_type, treatment_batch_id, transformation_id, performed_at, responsible, note)
    values
      (p_product_id, 'pending_treatment', -p_quantity, 'treatment_out', v_batch_id, v_transformation_id, coalesce(p_performed_at, now()), trim(p_responsible), nullif(trim(p_note), '')),
      (p_product_id, 'ready', p_quantity, 'treatment_in', v_batch_id, v_transformation_id, coalesce(p_performed_at, now()), trim(p_responsible), nullif(trim(p_note), ''));
  end if;

  return jsonb_build_object(
    'batchId', v_batch_id,
    'status', v_status,
    'transformationId', case when v_status = 'posted' then v_transformation_id else null end,
    'previousPending', v_pending_before,
    'newPending', v_pending_before - case when v_status = 'posted' then p_quantity else 0 end,
    'previousReady', v_ready_before,
    'newReady', v_ready_before + case when v_status = 'posted' then p_quantity else 0 end
  );
end; $$;

create or replace function public.reverse_treatment_batch_v1(
  p_batch_id bigint,
  p_performed_at timestamptz,
  p_responsible text,
  p_note text
) returns jsonb language plpgsql security invoker set search_path = public as $$
declare
  v_original public.treatment_batches%rowtype;
  v_reversal_id bigint;
  v_transformation_id uuid := gen_random_uuid();
  v_pending_before integer;
  v_ready_before integer;
begin
  if nullif(trim(p_responsible), '') is null or nullif(trim(p_note), '') is null then
    raise exception 'Responsable y motivo son obligatorios para revertir.';
  end if;
  select * into v_original from public.treatment_batches where id = p_batch_id for share;
  if not found then raise exception 'Lote no encontrado.'; end if;
  if v_original.status <> 'posted' then raise exception 'Solo se revierte un lote confirmado.'; end if;
  if exists (select 1 from public.treatment_batches where reversal_of_batch_id = p_batch_id) then raise exception 'El lote ya fue revertido.'; end if;

  perform 1 from public.products where id = v_original.product_id for update;
  select coalesce(sum(quantity), 0) into v_pending_before
  from public.stock_movements where product_id = v_original.product_id and stock_state = 'pending_treatment';
  select coalesce(sum(quantity), 0) into v_ready_before
  from public.stock_movements where product_id = v_original.product_id and stock_state = 'ready';
  if v_ready_before < v_original.quantity then raise exception 'El stock listo ya no alcanza; use un ajuste autorizado de stock.'; end if;

  insert into public.treatment_batches(
    product_id, client_product_id, order_line_id, quantity, performed_at, responsible, status, note, reversal_of_batch_id
  ) values (
    v_original.product_id, v_original.client_product_id, v_original.order_line_id, v_original.quantity,
    coalesce(p_performed_at, now()), trim(p_responsible), 'reversal', trim(p_note), p_batch_id
  ) returning id into v_reversal_id;

  insert into public.stock_movements(product_id, stock_state, quantity, movement_type, treatment_batch_id, transformation_id, performed_at, responsible, note)
  values
    (v_original.product_id, 'ready', -v_original.quantity, 'treatment_reversal_out', v_reversal_id, v_transformation_id, coalesce(p_performed_at, now()), trim(p_responsible), trim(p_note)),
    (v_original.product_id, 'pending_treatment', v_original.quantity, 'treatment_reversal_in', v_reversal_id, v_transformation_id, coalesce(p_performed_at, now()), trim(p_responsible), trim(p_note));

  return jsonb_build_object(
    'batchId', v_reversal_id,
    'status', 'reversal',
    'transformationId', v_transformation_id,
    'previousPending', v_pending_before,
    'newPending', v_pending_before + v_original.quantity,
    'previousReady', v_ready_before,
    'newReady', v_ready_before - v_original.quantity
  );
end; $$;

create or replace function public.complete_production_allocation_v1(
  p_allocation_id bigint,
  p_actual_quantity integer,
  p_completion_note text
) returns boolean language plpgsql security invoker set search_path = public as $$
declare
  v_allocation public.production_allocations%rowtype;
  v_product_id text;
  v_requires_treatment boolean;
  v_state text;
begin
  select * into v_allocation from public.production_allocations where id = p_allocation_id for update;
  if not found then raise exception 'Asignación no encontrada.'; end if;
  if v_allocation.status <> 'confirmed' then raise exception 'Solo se completan asignaciones confirmadas.'; end if;
  if p_actual_quantity is null or p_actual_quantity < 0 or p_actual_quantity > v_allocation.planned_quantity then
    raise exception 'La cantidad real debe estar entre cero y la cantidad planificada.';
  end if;
  if p_actual_quantity <> v_allocation.planned_quantity and nullif(trim(p_completion_note), '') is null then
    raise exception 'Explique la diferencia entre lo planificado y lo producido.';
  end if;
  select ol.product_id, p.requires_treatment into v_product_id, v_requires_treatment
  from public.order_lines ol join public.products p on p.id = ol.product_id
  where ol.id = v_allocation.order_line_id;
  if v_product_id is null then raise exception 'La línea no está vinculada a un producto del maestro.'; end if;

  if p_actual_quantity > 0 then
    perform 1 from public.products where id = v_product_id for update;
    v_state := case when v_requires_treatment then 'pending_treatment' else 'ready' end;
    insert into public.stock_movements(
      product_id, stock_state, quantity, movement_type, production_allocation_id,
      transformation_id, performed_at, responsible, note
    ) values (
      v_product_id, v_state, p_actual_quantity, 'production_receipt', p_allocation_id,
      gen_random_uuid(), now(), 'Producción', coalesce(nullif(trim(p_completion_note), ''), 'Producción completada')
    );
  end if;

  update public.production_allocations set
    actual_quantity = p_actual_quantity,
    completed_at = now(),
    completion_note = nullif(trim(p_completion_note), ''),
    status = 'completed'
  where id = p_allocation_id;
  return true;
end; $$;

create or replace function public.create_catalog_product_v2(
  p_kind text,
  p_measure text,
  p_requires_treatment boolean
) returns text language plpgsql security invoker set search_path = public as $$
declare v_id text; v_measure text := nullif(trim(p_measure), '');
begin
  if p_kind not in ('Pallet', 'Piso', 'Bin') then raise exception 'El tipo indicado no es válido.'; end if;
  if exists (select 1 from public.products where kind = p_kind and measure is not distinct from v_measure) then
    raise exception 'Ya existe un producto con ese tipo y medida.';
  end if;
  v_id := 'producto-' || floor(extract(epoch from clock_timestamp()) * 1000)::bigint || '-' || left(replace(gen_random_uuid()::text, '-', ''), 6);
  insert into public.products(id, kind, measure, requires_treatment)
  values (v_id, p_kind, v_measure, coalesce(p_requires_treatment, false));
  return v_id;
end; $$;

create or replace function public.update_catalog_product_v2(
  p_id text,
  p_kind text,
  p_measure text,
  p_requires_treatment boolean
) returns text language plpgsql security invoker set search_path = public as $$
declare v_id text;
begin
  if p_kind not in ('Pallet', 'Piso', 'Bin') then raise exception 'El tipo indicado no es válido.'; end if;
  update public.products set
    kind = p_kind,
    measure = nullif(trim(p_measure), ''),
    requires_treatment = coalesce(p_requires_treatment, false)
  where id = p_id returning id into v_id;
  if v_id is null then raise exception 'Producto no encontrado.'; end if;
  return v_id;
end; $$;

create or replace function public.create_operation_order_v5(
  p_lines jsonb, p_order_date date, p_requested_delivery_date date, p_production_date date,
  p_planned_date date, p_reference text, p_notes text, p_stage text, p_production_source text,
  p_producer_provider_id text, p_import_arrival_date date, p_required_operations text[],
  p_transport_source text, p_transport_provider_id text
) returns text language plpgsql security invoker set search_path = public as $$
declare v_id text; v_legacy_operations text[];
begin
  if cardinality(p_required_operations) = 0 or not (p_required_operations <@ array['assembly','treatment']::text[]) then
    raise exception 'Seleccione operaciones válidas.';
  end if;
  v_legacy_operations := array(
    select distinct case when operation = 'treatment' then 'marking' else operation end
    from unnest(p_required_operations) operation order by 1
  );
  v_id := public.create_operation_order_v4(
    p_lines, p_order_date, p_requested_delivery_date, p_production_date, p_planned_date,
    p_reference, p_notes, p_stage, p_production_source, p_producer_provider_id,
    p_import_arrival_date, v_legacy_operations, p_transport_source, p_transport_provider_id
  );
  update public.orders set
    required_operations = p_required_operations,
    preparation = 'Operaciones: ' || array_to_string(p_required_operations, ', ')
  where id = v_id;
  return v_id;
end; $$;

create or replace function public.update_operation_order_v3(
  p_id text, p_planned_date date, p_requested integer, p_stage text,
  p_production_source text, p_producer_provider_id text, p_production_date date,
  p_import_arrival_date date, p_required_operations text[], p_transport_source text,
  p_transport_provider_id text
) returns text language plpgsql security invoker set search_path = public as $$
declare
  v_before public.orders%rowtype; v_after public.orders%rowtype; v_transport text;
  v_change_id uuid; v_position integer := 10;
begin
  select * into v_before from public.orders where id = p_id;
  if not found then raise exception 'Pedido no encontrado.'; end if;
  if p_production_source in ('internal','sawmill') and p_production_date is null then raise exception 'Indique la fecha de producción.'; end if;
  if p_production_source = 'sawmill' and not exists (select 1 from public.providers where id = p_producer_provider_id and type = 'Aserradero') then raise exception 'Seleccione un aserradero registrado.'; end if;
  if p_production_source = 'import' and (p_import_arrival_date is null or not exists (select 1 from public.providers where id = p_producer_provider_id and type = 'Importador')) then raise exception 'Seleccione importador y fecha prevista de llegada.'; end if;
  if p_transport_source = 'external' and not exists (select 1 from public.providers where id = p_transport_provider_id and type = 'Transporte') then raise exception 'Seleccione un transportista registrado.'; end if;
  if cardinality(p_required_operations) = 0 or not (p_required_operations <@ array['assembly','treatment']::text[]) then raise exception 'Operaciones inválidas.'; end if;
  select name into v_transport from public.providers where id = p_transport_provider_id;
  v_transport := case when p_transport_source = 'internal' then 'Interno' else v_transport end;
  perform public.update_operation_order(p_id, null, case when p_transport_source = 'external' then v_transport else null end, p_planned_date, p_requested, p_stage);
  select * into v_after from public.orders where id = p_id;
  if p_transport_source = 'internal' and v_after.transport <> 'Interno' then update public.orders set transport = 'Interno', logistics = 'Interno · entrega planificada' where id = p_id; end if;
  if v_before.production_source is distinct from p_production_source or v_before.producer_provider_id is distinct from p_producer_provider_id or v_before.production_date is distinct from p_production_date or v_before.import_arrival_date is distinct from p_import_arrival_date or v_before.required_operations is distinct from p_required_operations or v_before.transport_source is distinct from p_transport_source or v_before.transport_provider_id is distinct from p_transport_provider_id then
    insert into public.order_changes(order_id) values (p_id) returning id into v_change_id;
    if v_before.production_source is distinct from p_production_source then insert into public.order_change_items(change_id,field,from_value,to_value,position) values(v_change_id,'Origen de producción',v_before.production_source,p_production_source,v_position); v_position:=v_position+1; end if;
    if v_before.producer_provider_id is distinct from p_producer_provider_id then insert into public.order_change_items(change_id,field,from_value,to_value,position) values(v_change_id,'Productor',coalesce((select name from public.providers where id=v_before.producer_provider_id),'—'),coalesce((select name from public.providers where id=p_producer_provider_id),'Ecoase'),v_position); v_position:=v_position+1; end if;
    if v_before.production_date is distinct from p_production_date then insert into public.order_change_items(change_id,field,from_value,to_value,position) values(v_change_id,'Fecha de producción',coalesce(v_before.production_date::text,'—'),coalesce(p_production_date::text,'—'),v_position); v_position:=v_position+1; end if;
    if v_before.import_arrival_date is distinct from p_import_arrival_date then insert into public.order_change_items(change_id,field,from_value,to_value,position) values(v_change_id,'Llegada de importación',coalesce(v_before.import_arrival_date::text,'—'),coalesce(p_import_arrival_date::text,'—'),v_position); v_position:=v_position+1; end if;
    if v_before.required_operations is distinct from p_required_operations then insert into public.order_change_items(change_id,field,from_value,to_value,position) values(v_change_id,'Operaciones',array_to_string(v_before.required_operations,', '),array_to_string(p_required_operations,', '),v_position); v_position:=v_position+1; end if;
    if v_before.transport_source is distinct from p_transport_source then insert into public.order_change_items(change_id,field,from_value,to_value,position) values(v_change_id,'Origen del transporte',v_before.transport_source,p_transport_source,v_position); v_position:=v_position+1; end if;
    if v_before.transport_provider_id is distinct from p_transport_provider_id then insert into public.order_change_items(change_id,field,from_value,to_value,position) values(v_change_id,'Transportista',coalesce((select name from public.providers where id=v_before.transport_provider_id),'Interno'),coalesce((select name from public.providers where id=p_transport_provider_id),'Interno'),v_position); v_position:=v_position+1; end if;
  end if;
  update public.orders set
    production_source=p_production_source, producer_provider_id=p_producer_provider_id,
    production_date=p_production_date, import_arrival_date=p_import_arrival_date,
    required_operations=p_required_operations, transport_source=p_transport_source,
    transport_provider_id=p_transport_provider_id, transport=v_transport, updated_at=now()
  where id=p_id;
  return p_id;
end; $$;

revoke execute on function public.record_treatment_batch_v1(text,bigint,text,integer,timestamptz,text,text,jsonb) from public, anon, authenticated;
revoke execute on function public.reverse_treatment_batch_v1(bigint,timestamptz,text,text) from public, anon, authenticated;
revoke execute on function public.create_catalog_product_v2(text,text,boolean) from public, anon, authenticated;
revoke execute on function public.update_catalog_product_v2(text,text,text,boolean) from public, anon, authenticated;
revoke execute on function public.create_operation_order_v5(jsonb,date,date,date,date,text,text,text,text,text,date,text[],text,text) from public, anon, authenticated;
revoke execute on function public.update_operation_order_v3(text,date,integer,text,text,text,date,date,text[],text,text) from public, anon, authenticated;

grant execute on function public.record_treatment_batch_v1(text,bigint,text,integer,timestamptz,text,text,jsonb) to service_role;
grant execute on function public.reverse_treatment_batch_v1(bigint,timestamptz,text,text) to service_role;
grant execute on function public.create_catalog_product_v2(text,text,boolean) to service_role;
grant execute on function public.update_catalog_product_v2(text,text,text,boolean) to service_role;
grant execute on function public.create_operation_order_v5(jsonb,date,date,date,date,text,text,text,text,text,date,text[],text,text) to service_role;
grant execute on function public.update_operation_order_v3(text,date,integer,text,text,text,date,date,text[],text,text) to service_role;

notify pgrst, 'reload schema';
