create table public.products (
  id text primary key,
  code text not null,
  name text not null,
  kind text not null check (kind in ('Pallet', 'Piso', 'Bin')),
  measure text,
  assignment text,
  specification text,
  treatment text check (treatment is null or treatment in ('Marcado', 'HT')),
  catalog text not null check (catalog in ('Palbin', 'Pamer')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products enable row level security;
create policy products_public_read on public.products for select to anon, authenticated using (true);
grant select on public.products to anon, authenticated;

insert into public.products (id, code, name, kind, measure, assignment, specification, treatment, catalog) values
  ('palbin-p01','P01','Cristal PET','Pallet','106 × 119','Cristal PET',null,'Marcado','Palbin'),
  ('palbin-p02','P02','Palets Citrus','Pallet','120 × 100','Citrus',null,'Marcado','Palbin'),
  ('palbin-p03','P03','Molinos San José','Pallet','120 × 100','Molinos San José',null,'Marcado','Palbin'),
  ('palbin-p04','P04','Saint Gobain','Pallet','106 × 106','Saint Gobain',null,null,'Palbin'),
  ('palbin-p05','P05','122 × 102','Pallet','122 × 102',null,null,'Marcado','Palbin'),
  ('palbin-p06','P06','Reparados','Pallet','120 × 100',null,null,null,'Palbin'),
  ('palbin-p07','P07','Granja Pocha punto rojo','Pallet',null,'Granja Pocha',null,'Marcado','Palbin'),
  ('palbin-p08','P08','Azucarlito','Pallet',null,'Azucarlito',null,'Marcado','Palbin'),
  ('palbin-p09','P09','Pisos exportación','Piso',null,'Exportación',null,'Marcado','Palbin'),
  ('palbin-p10','P10','Fricasa','Pallet','120 × 100','Fricasa',null,'Marcado','Palbin'),
  ('palbin-p11','P11','Proquimur','Pallet','120 × 100','Proquimur',null,'Marcado','Palbin'),
  ('palbin-p12','P12','Conaprole','Pallet','120 × 100','Conaprole',null,'Marcado','Palbin'),
  ('palbin-p13','P13','120 × 80','Pallet','120 × 80',null,null,'Marcado','Palbin'),
  ('palbin-p14','P14','Pisos Chacra','Piso',null,'Chacra',null,null,'Palbin'),
  ('palbin-p15','P15','Bins X3 exportación','Bin',null,'Exportación',null,'Marcado','Palbin'),
  ('palbin-p16','P16','Bins X2 exportación','Bin',null,'Exportación',null,'Marcado','Palbin'),
  ('palbin-p17','P17','Bins Chacra azul','Bin',null,'Chacra',null,null,'Palbin'),
  ('palbin-p18','P18','Bins Chacra blanco','Bin',null,'Chacra',null,null,'Palbin'),
  ('palbin-p19','P19','Bins Chacra rojo','Bin',null,'Chacra',null,null,'Palbin'),
  ('palbin-p20','P20','Bins Chacra anaranjado','Bin',null,'Chacra',null,null,'Palbin'),
  ('palbin-p21','P21','AFB','Pallet','120 × 100','AFB',null,'Marcado','Palbin'),
  ('palbin-p22','P22','AFB','Pallet','220 × 117','AFB',null,'Marcado','Palbin'),
  ('palbin-p23','P23','Pallet tipo MSJ Mirasol','Pallet','120 × 120','Mercosur con rebaje en todas las tablas MSJ',null,'Marcado','Palbin'),
  ('palbin-p24','P24','Bins Lio X3','Bin',null,'Lio',null,'Marcado','Palbin'),
  ('palbin-p25','P25','Pallet Citrus','Pallet','103 × 121','Citrus',null,'Marcado','Palbin'),
  ('palbin-p26','P26','Pallet número 6','Pallet','122 × 102','Azucitrus',null,'Marcado','Palbin'),
  ('palbin-p27','P27','Pallet Mercosur con corte','Pallet','120 × 100',null,null,'Marcado','Palbin'),
  ('palbin-p28','P28','Pallet Mercosur sin corte','Pallet','120 × 100',null,null,'Marcado','Palbin'),
  ('palbin-p29','P29','Aluminios del Uruguay','Pallet','120 × 100',null,null,'Marcado','Palbin'),
  ('palbin-p30','P30','San Miguel','Pallet','113 × 113',null,null,'Marcado','Palbin'),
  ('palbin-p31','P31','Pallet 120 × 130','Pallet','120 × 130',null,null,'Marcado','Palbin'),
  ('palbin-p32','P32','Pallet 112 × 120','Pallet','112 × 120',null,null,'Marcado','Palbin'),
  ('palbin-p33','P33','San Miguel','Pallet','116,5 × 114',null,null,'Marcado','Palbin'),
  ('palbin-p34','P34','San Miguel','Pallet','120 × 120',null,null,null,'Palbin'),
  ('palbin-p35','P35','San Miguel reforzado','Pallet','120 × 120',null,null,null,'Palbin'),
  ('palbin-p36','P36','Pallet Preinco','Pallet','120 × 100','Preinco',null,'Marcado','Palbin'),
  ('palbin-p37','P37','Bins Chacra Chapicuy','Bin',null,'Frutos del Chapicuy',null,null,'Palbin'),
  ('palbin-p38','P38','Pallet MSJ','Pallet','220 × 120','Molinos San José',null,'Marcado','Palbin'),
  ('palbin-p39','P39','Avanti','Pallet','120 × 100','Avanti',null,'Marcado','Palbin'),
  ('pamer-p01','P01','100 × 80 abiertas','Pallet','100 × 80','Pamer','Abiertas','HT','Pamer'),
  ('pamer-p02','P02','100 × 100 abiertas','Pallet','100 × 100','Pamer','Abiertas','HT','Pamer'),
  ('pamer-p03','P03','100 × 120 Mercosur liviano','Pallet','100 × 120','Pamer','Mercosur liviano','HT','Pamer'),
  ('pamer-p04','P04','120 × 100 Adium reforzado','Pallet','120 × 100','Pamer','Adium reforzado','HT','Pamer'),
  ('pamer-p05','P05','120 × 80 abiertas','Pallet','120 × 80','Pamer','Abiertas','HT','Pamer'),
  ('pamer-p06','P06','120 × 80 cerradas','Pallet','120 × 80','Pamer','Cerradas','HT','Pamer'),
  ('pamer-p07','P07','120 × 90 cerradas','Pallet','120 × 90','Pamer','Cerradas','HT','Pamer'),
  ('pamer-p08','P08','120 × 100 abiertas','Pallet','120 × 100','Pamer','Abiertas','HT','Pamer'),
  ('pamer-p09','P09','120 × 100 cerradas','Pallet','120 × 100','Pamer','Cerradas','HT','Pamer'),
  ('pamer-p10','P10','120 × 120 cerradas','Pallet','120 × 120','Pamer','Cerradas','HT','Pamer'),
  ('pamer-p11','P11','120 × 120 abiertas','Pallet','120 × 120','Pamer','Abiertas','HT','Pamer'),
  ('pamer-p12','P12','130 × 90 cerradas','Pallet','130 × 90','Pamer','Cerradas','HT','Pamer'),
  ('pamer-p13','P13','140 × 120 abiertas','Pallet','140 × 120','Pamer','Abiertas','HT','Pamer'),
  ('pamer-p14','P14','140 × 120 cerradas','Pallet','140 × 120','Pamer','Cerradas','HT','Pamer'),
  ('pamer-p15','P15','145 × 80 abiertas reforzadas','Pallet','145 × 80','Pamer','Abiertas reforzadas','HT','Pamer'),
  ('pamer-p16','P16','145 × 100 abiertas','Pallet','145 × 100','Pamer','Abiertas','HT','Pamer'),
  ('pamer-p17','P17','145 × 100 cerradas','Pallet','145 × 100','Pamer','Cerradas','HT','Pamer'),
  ('pamer-p18','P18','155 × 70 abiertas','Pallet','155 × 70','Pamer','Abiertas','HT','Pamer'),
  ('pamer-p19','P19','160 × 80 abiertas','Pallet','160 × 80','Pamer','Abiertas','HT','Pamer'),
  ('pamer-p20','P20','160 × 110 simples reforzadas','Pallet','160 × 110','Pamer','Simples reforzadas','HT','Pamer'),
  ('pamer-p21','P21','216 × 110 simples reforzadas','Pallet','216 × 110','Pamer','Simples reforzadas','HT','Pamer'),
  ('pamer-p22','P22','130 × 120','Pallet','130 × 120','Pamer',null,null,'Pamer')
on conflict (id) do update set
  code = excluded.code,
  name = excluded.name,
  kind = excluded.kind,
  measure = excluded.measure,
  assignment = excluded.assignment,
  specification = excluded.specification,
  treatment = excluded.treatment,
  catalog = excluded.catalog,
  updated_at = now();
